[GAME]
; default is 15, DO NOT GIVE EVEN NUMBER
MAP_WIDTH = 11

# default is 5, you can put any number
MAP_HEIGHT = 6

; default is 0.3, WARNING DO NOT CHANGE THIS BY A LOT
BALL_SPEED = 0.3

; "WINDOWS" = 1 or "MAC" = 2, basically it just changes the clearing system
OS_MODE = 1